enum Tile_Type {	  
BLOCKED_CELL,
TUNNEL_HORIZONTAL, # --
TUNNEL_VERTICAL, # |
CORNER_TOP_LEFT, # |¯
CORNER_TOP_RIGHT, # ¯|
CORNER_BOTTOM_LEFT, # |_
CORNER_BOTTOM_RIGHT, # _|
T_NORMAL, # ¯|¯
T_LEFT, # |-
T_RIGHT, # -|
T_UPSIDE_DOWN, # _|_
CROSSROAD, # -|-
}
